[package]
name = "lv8"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
v8 = "129.0.0"

# wasi related
wasi-common = "22.0.0"
cap-std = "3.2.0"
tokio = { version = "1.0", features = ["full"] }
wiggle = "22.0.0"
